import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ToastContainer } from "react-toastify";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        cz-shortcut-listen="true"
        style={{
          height: "100vh",
          overflow: "auto",
          scrollbarWidth: "none", // Untuk Firefox
          msOverflowStyle: "none", // Untuk IE & Edge
        }}
      >
        {children}
        <ToastContainer />
      </body>
    </html>
  );
}
